default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: 123456
  host: localhost
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: alavadeira_sbadmin2_development

test:
  <<: *default
  database: alavadeira_sbadmin2_test

production:
  <<: *default
  database: alavadeira_sbadmin2_production
  username: alavadeira_sbadmin2
  password: <%= ENV['ALAVADEIRA_SBADMIN2_DATABASE_PASSWORD'] %>
